// Code generated by "stringer -type=OpCode"; DO NOT EDIT.

package dnsmsg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Query-0]
	_ = x[IQuery-1]
	_ = x[Status-2]
}

const _OpCode_name = "QueryIQueryStatus"

var _OpCode_index = [...]uint8{0, 5, 11, 17}

func (i OpCode) String() string {
	if i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
